from rest_framework import serializers
from .models import Listing, Booking, Payment

class ListingSerializer(serializers.ModelSerializer):
    class Meta:
        model = Listing
        fields = '__all__'

class BookingSerializer(serializers.ModelSerializer):
    class Meta:
        model = Booking
        fields = '__all__'

class PaymentSerializer(serializers.ModelSerializer):
    class Meta:
        model = Payment
        fields = ['id', 'booking', 'transaction_id', 'amount', 'status', 'created_at']
        read_only_fields = ['transaction_id', 'status', 'amount', 'created_at']
        # Note: transaction_id, status, and amount are read-only because they are 
        # generated by our backend logic, not input by the user.